name: Build Package

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Package Name'
        required: true
      version:
        description: 'Package Version'
        required: true
      keyword:
        description: 'Package KeyWord'
        required: true

jobs:
  build-package:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Apt Install
      run: |
        sudo apt install fakeroot

    - name: Build Folder
      continue-on-error: true
      run: |
        cd ${{ github.event.inputs.name }}
        mkdir build

    - name: Build Package
      run: |
        cd ${{ github.event.inputs.name }}
        fakeroot dpkg-deb --build package ./build
        cd build
        md5sum ${{ github.event.inputs.name }}_${{ github.event.inputs.version }}_all.deb >> MD5SUM
        echo "Build Success!"
    
    - name: Commit and push changes
      run: |
        sudo git config user.name auto-push
        sudo git config user.email auto-push@example.com
        sudo git add .
        sudo git commit -m "auto push from ci" || echo no commits
        sudo git push

    - name: Make Directory
      continue-on-error: true
      run: |
        mkdir -p pool/main/${{ github.event.inputs.keyword }}/${{ github.event.inputs.name }}/

    - name: Copy Package
      run: |
        cd ${{ github.event.inputs.name }}/build
        cp ${{ github.event.inputs.name }}_${{ github.event.inputs.version }}_all.deb ../../pool/main/${{ github.event.inputs.keyword }}/${{ github.event.inputs.name }}/${{ github.event.inputs.name }}_${{ github.event.inputs.version }}_all.deb
        cp MD5SUM ../../pool/main/${{ github.event.inputs.keyword }}/${{ github.event.inputs.name }}/MD5SUM

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Ensure build branch exists
      run: |
        git fetch origin build:build || echo "No remote build branch found"

        if git ls-remote --exit-code --heads origin build; then
          sudo git stash -u
          sudo rm -f pool/main/p/port/MD5SUM
          sudo rm -f pool/main/p/port/port_1.0.0_all.deb
          git checkout build
          git stash apply
        else
          git checkout --orphan build
          git reset --hard
          git commit --allow-empty -m "Initial commit for build branch"
          git push origin build
        fi


    - name: Copy power-root to build branch
      run: |
        ls | grep -i -v -E 'pool|.git' | xargs sudo rm -rf
        
        git add .
        git commit -m "Update build branch from specific-folder" || echo "No changes to commit"

    - name: Push to build branch
      run: |
        git push origin build

