name: Minecraft Server List

on:
  workflow_dispatch:

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5.3.0

      - name: Run Command
        run: |
          pip install pandas
          cd minecraft-server
          wget https://gist.githubusercontent.com/cliffano/77a982a7503669c3e1acb0a0cf6127e9/raw/1868a831baa6ab466e506e638116e35ceaf025cd/minecraft-server-jar-downloads.md
          python package.py
          rm minecraft-server-jar-downloads.md

      - name: Commit and push changes
        run: |
          git config user.name "auto-push"
          git config user.email "auto-push@example.com"
          git add .
          git commit -m "auto push from ci" || echo "No changes to commit"
          git push
          
